version: '3'

services:
  mongodb:
    container_name: mongodb_cs6
    image: mongodb/mongodb-community-server:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root_user
      - MONGO_INITDB_ROOT_PASSWORD=root_pass
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb_data:/data/db